
name: app-testing
on: push
jobs:
  pytest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Pytest run
        run: pytest -v -s
